api:
    consumer_key: nJRGQam9ssMQUsefONafII4r5
    consumer_secret: ivHXnY6MXVRYrdyxTrBxzstn52jOpnwQdSJ0KVYq8OLuP7OFhM
    access_token_path: ./token/token.csv
db:
    host: mariadb
    user: root
    password: admin
    database: twitter
    user_table: users
    profile_table: profiles
    tweets_table: tweets
    charset: utf8mb4
