version: 1
formatters:
  simple:
    format: '[%(asctime)s|%(name)s|%(levelname)s] %(message)s'

loggers:
  file:
    handlers: [fileRotatingHandler]
    level: DEBUG
    qualname: file
    propagate: no

  console:
    handlers: [consoleHandler]
    level: DEBUG
    qualname: console
    propagate: no

  collector:
    handlers: [fileRotatingHandler, consoleHandler]
    level: DEBUG
    propagate: no
  

handlers:
  fileRotatingHandler:
    formatter: simple
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    filename: ./log/debug.log
    encoding: utf8
    when: 'H'
    interval: 1
    backupCount: 24

  consoleHandler:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

root:
  level: DEBUG
  handlers: [fileRotatingHandler,consoleHandler]
